using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SceneManagement;
﻿using System.Collections;
using System.Collections.Generic;
public class main:MonoBehaviour{
  public int counter;
  public Text textoutput0;
  public Text textoutput1;
  void Start(){
    Scene scene = SceneManager.GetActiveScene();
    if (scene.name=="Scene1"){
      counter=50;
      }
    }
  void Update(){
    textoutput0.text=counter.ToString("F0");

    Scene scene = SceneManager.GetActiveScene();
    textoutput1.text=scene.name;
    if(counter>=100){
      if (scene.name=="Scene1"){
        SceneManager.LoadScene("Scene2");
        }
      if (scene.name=="Scene2"){
        SceneManager.LoadScene("Scene1");
        }
      }
    counter+=1;
    }}

