using System.Collections;using System.Collections.Generic;
using UnityEngine;using UnityEngine.SceneManagement;

public class LoadScene2 : MonoBehaviour{
    // Start is called before the first frame update

    void Awake(){
        SceneManager.LoadScene("Scenes/Scene2");
        //SceneManager.LoadScene(scenename);
        }

    void Start(){
        //SceneManager.LoadScene("Scenes/Scene2");
        //SceneManager.LoadScene(scenename);
        }

    // Update is called once per frame
    void Update(){
        }}




