using UnityEngine;
using UnityEngine.UI; 
using System.Collections;
public class changetext2:MonoBehaviour{
  //private Text m_TextComponent;
  public Text m_TextComponent;
  public int contador;

  void Awake(){   
    m_TextComponent=GetComponent<Text>();
    m_TextComponent.text="Lorem ipsum dolor sit amet";
    }
  // Start is called before the first frame update
  void Start(){
    //contador=5;
    }
  void Update(){
    //m_TextComponent.text="1";
    //contador+=1;
    //m_TextComponent.text=coordenada1.x.ToString();
    }}
 

