using System.Collections;using System.Collections.Generic;
using UnityEngine;using UnityEngine.SceneManagement;

public class LoadScene : MonoBehaviour{

  public GameObject cena;

    void Awake(){
        SceneManager.LoadScene(cena.name);

        //SceneManager.LoadScene("Scenes/Scene2");
        //SceneManager.LoadScene(scenename);
        }

    void Start(){
        //SceneManager.LoadScene("Scenes/Scene2");
        //SceneManager.LoadScene(scenename);
        }

    void Update(){}

    void FixedUpdate(){}
    }



﻿

