using UnityEngine;
using UnityEngine.UI; // The namespace for the UI stuff.
using System.Collections;
public class changetext1 : MonoBehaviour{
    //private Text m_TextComponent;
    public Text m_TextComponent;
    public int contador;
    void Awake(){
        // Get a reference to the text component
        m_TextComponent = GetComponent<Text>();
        m_TextComponent.text = "This is the new text.";
    }
    // Start is called before the first frame update
    void Start(){
          contador=5;
    }
    // Update is called once per frame
    void Update(){
        //m_TextComponent.text = "1";
        contador+=1;
        m_TextComponent.text = contador.ToString();
    }}
 

